import jsPDF from 'jspdf'
import { AnalysisResult, Decision } from '@/types'

export async function generateDecisionPDF(decision: Decision, result: AnalysisResult): Promise<void> {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20
  let yPosition = margin

  // Title
  pdf.setFontSize(20)
  pdf.setFont('helvetica', 'bold')
  pdf.text('PathFinder Decision Analysis', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 15

  // Decision Title
  pdf.setFontSize(16)
  pdf.text(`Decision: ${decision.title}`, margin, yPosition)
  yPosition += 10

  // Context
  pdf.setFontSize(12)
  pdf.setFont('helvetica', 'normal')
  const contextLines = pdf.splitTextToSize(decision.context, pageWidth - 2 * margin)
  pdf.text(contextLines, margin, yPosition)
  yPosition += contextLines.length * 6 + 10

  // Options
  pdf.setFont('helvetica', 'bold')
  pdf.text('Options Considered:', margin, yPosition)
  yPosition += 8
  pdf.setFont('helvetica', 'normal')
  decision.options.forEach((option, index) => {
    pdf.text(`${index + 1}. ${option}`, margin + 10, yPosition)
    yPosition += 6
  })
  yPosition += 10

  // Priorities
  pdf.setFont('helvetica', 'bold')
  pdf.text('Priorities (Weighted):', margin, yPosition)
  yPosition += 8
  pdf.setFont('helvetica', 'normal')
  decision.priorities.forEach((priority, index) => {
    pdf.text(`${priority.name}: ${priority.weight}/10 - ${priority.description}`, margin + 10, yPosition)
    yPosition += 6
  })
  yPosition += 15

  // Check if we need a new page
  if (yPosition > 200) {
    pdf.addPage()
    yPosition = margin
  }

  // Analysis Results
  pdf.setFont('helvetica', 'bold')
  pdf.text('Analysis Results:', margin, yPosition)
  yPosition += 10

  // Scores Table
  const tableTop = yPosition
  const colWidth = 40
  const startX = margin
  
  // Header
  pdf.setFontSize(10)
  pdf.text('Option', startX, tableTop)
  pdf.text('Overall', startX + colWidth, tableTop)
  decision.priorities.forEach((priority, idx) => {
    pdf.text(priority.name.substring(0, 8), startX + colWidth * (idx + 2), tableTop)
  })
  
  yPosition += 6

  // Data rows
  result.scores.forEach((score) => {
    if (yPosition > 250) {
      pdf.addPage()
      yPosition = margin + 10
    }
    
    pdf.text(score.option.substring(0, 12), startX, yPosition)
    pdf.text(score.overall_score.toString(), startX + colWidth, yPosition)
    
    decision.priorities.forEach((priority, idx) => {
      const priorityScore = score.priority_scores?.[priority.name] || 0
      pdf.text(priorityScore.toString(), startX + colWidth * (idx + 2), yPosition)
    })
    
    yPosition += 6
  })

  yPosition += 10

  // Recommendation
  pdf.setFont('helvetica', 'bold')
  pdf.text(`Recommended Option: ${result.recommended_option}`, margin, yPosition)
  yPosition += 8

  // Confidence
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Confidence Level: ${result.confidence}%`, margin, yPosition)
  yPosition += 10

  // Summary
  const summaryLines = pdf.splitTextToSize(result.summary, pageWidth - 2 * margin)
  pdf.text('Summary:', margin, yPosition)
  yPosition += 6
  pdf.text(summaryLines, margin, yPosition)
  yPosition += summaryLines.length * 6 + 10

  // Reasoning (if available)
  if (result.reasoning) {
    if (yPosition > 200) {
      pdf.addPage()
      yPosition = margin
    }
    
    pdf.setFont('helvetica', 'bold')
    pdf.text('Detailed Reasoning:', margin, yPosition)
    yPosition += 6
    pdf.setFont('helvetica', 'normal')
    const reasoningLines = pdf.splitTextToSize(result.reasoning, pageWidth - 2 * margin)
    pdf.text(reasoningLines, margin, yPosition)
  }

  // Footer
  pdf.setFontSize(8)
  pdf.setTextColor(128, 128, 128)
  pdf.text(
    `Generated by PathFinder on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pdf.internal.pageSize.getHeight() - 10,
    { align: 'center' }
  )

  // Save the PDF
  const filename = `pathfinder-${decision.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`
  pdf.save(filename)
}